import { StyleSheet, Font } from '@react-pdf/renderer';

// Using react-pdf's built-in Helvetica family keeps this dependency-free (no font file hosting needed).
export const colors = {
  ink: '#1a1a1a',
  muted: '#6b6b66',
  hint: '#9a9a94',
  border: '#dddddd',
  borderStrong: '#bbbbbb',
  surface: '#ffffff',
  surface1: '#f4f3ee',
  accentBg: '#e6f1fb',
  accentText: '#0c447c',
  accentBorder: '#85b7eb',
};

export const styles = StyleSheet.create({
  page: {
    padding: 28,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: colors.ink,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 2.5,
    borderBottomColor: colors.ink,
    paddingBottom: 8,
    marginBottom: 12,
  },
  ringName: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
  },
  subLabel: {
    fontSize: 8,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  subText: {
    fontSize: 9,
    color: colors.muted,
    marginTop: 2,
  },
  accentBadge: {
    backgroundColor: colors.accentBg,
    color: colors.accentText,
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  threeCol: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  twoCol: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  colBox: {
    flex: 1,
    backgroundColor: colors.surface1,
    borderRadius: 4,
    padding: 6,
  },
  colBoxLabel: {
    fontSize: 7.5,
    color: colors.muted,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  colBoxValue: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: colors.muted,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.ink,
    paddingBottom: 3,
    marginTop: 14,
    marginBottom: 6,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  statItem: {
    width: '33.3%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
    paddingRight: 8,
  },
  statItemHalf: {
    width: '50%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
    paddingRight: 8,
  },
  dots: {
    fontSize: 9,
    letterSpacing: 1,
  },
  star: {
    color: colors.accentText,
  },
  fieldBox: {
    borderWidth: 0.75,
    borderColor: colors.border,
    borderRadius: 4,
    padding: 5,
    minHeight: 28,
    fontSize: 8.5,
  },
  fieldLabel: {
    fontSize: 7.5,
    color: colors.muted,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
  },
  checkbox: {
    width: 8,
    height: 8,
    borderWidth: 1,
    borderColor: colors.muted,
    borderRadius: 1.5,
    marginRight: 5,
  },
  checkboxChecked: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  giftCard: {
    borderWidth: 0.75,
    borderColor: colors.border,
    borderRadius: 4,
    padding: 6,
    marginBottom: 5,
  },
  giftName: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
  },
  giftMeta: {
    fontSize: 7.5,
    color: colors.muted,
    marginTop: 1,
  },
  giftEffect: {
    fontSize: 8.5,
    marginTop: 2,
    lineHeight: 1.3,
  },
  gradeLabel: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    color: colors.accentText,
    backgroundColor: colors.accentBg,
    alignSelf: 'flex-start',
    borderRadius: 3,
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginTop: 8,
    marginBottom: 4,
  },
  table: {
    width: '100%',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderStrong,
    paddingBottom: 2,
    marginBottom: 3,
  },
  tableHeaderCell: {
    fontSize: 7.5,
    color: colors.muted,
    textTransform: 'uppercase',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    paddingVertical: 3,
  },
  tableCell: {
    fontSize: 8.5,
  },
  footerNote: {
    position: 'absolute',
    bottom: 16,
    left: 28,
    right: 28,
    fontSize: 7,
    color: colors.hint,
    textAlign: 'center',
  },
});
